name: Publish NPM

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - uses: actions/cache@v4
        with:
          path: |
            ~/.deno
            ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*.ts') }}
      - run: deno test

  publish:
    runs-on: ubuntu-latest

    needs: test

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      # Creates .npmrc with NODE_AUTH_TOKEN
      - uses: actions/setup-node@v4
        with:
          registry-url: "https://registry.npmjs.org"
      - uses: denoland/setup-deno@v2
      - name: Publish package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |-
          deno run -A dnt.ts
          cd dnt
          npm publish
